### ISSUE TITLE
Error while installing commonregex-improved package

### ISSUE THREAD

**Issue by likileads** [brootware/commonregex-improved#1]
I was using [commonregex](https://pypi.org/project/commonregex/) but it was raising an error when I import zip_code, ssn.

Then I went throught this [ReadMe ](https://github.com/brootware/commonregex-improved/blob/main/README.md) file, 
and followed the steps to install the package.

`pip install commonregex-improved`

> Collecting commonregex-improved
> Could not find a version that satisfies the requirement commonregex-improved (from versions: )
> No matching distribution found for commonregex-improved

<br>

`pip install --upgrade commonregex-improved`
Raising the same above error.

**Comment by likileads** [comment]
It is because of the python version I guess it is not working in 3.6x, but it is working fine in 3.8x

**Comment by brootware** [comment]
> It is because of the python version I guess it is not working in 3.6x, but it is working fine in 3.8x

Ah yes, the package requires python 3.7 and above. Can you confirm that you're able to install now? If so, will be closing this issue.

**Comment by likileads** [comment]
Yup it's working, I am able to install and use it.
