### ISSUE TITLE
Name collision with commonregex

### ISSUE THREAD

**Issue by erezsh** [brootware/commonregex-improved#2]
## Checklist

- [x] I have read the [README](https://github.com/brootware/PyMouseBot/blob/main/README.md) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/brootware/PyMouseBot/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

Hello, I'm thinking of using this package as a dependency, but currently cannot afford to do so -

Installing commonregex-improved might break existing uses of commonregex, and more importantly, later installations or updates of 
commonregex will break the access to commonregex-improved.

### Expected behavior

I think this package should use a different name for the import, like `commonregex_improved`.

If users really don't want to change their module references, they can import it as `import commonregex_improved as commonregex`.

### Additional context

I appreciate your improvements to the original, but right now I cannot use your package.

**Comment by brootware** [comment]
Hey @erezsh , thank you for letting me know of this issue. I have updated the naming convention. With the latest [patch](https://github.com/brootware/commonregex-improved/releases/tag/v1.0.1), You can now use `import crim as Commonregex` instead to cater for using original commonregex. :) Please update to the latest version and lemme know if it works for you.

**Comment by erezsh** [comment]
Great, thank you!
