### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by erezsh** [brootware/commonregex-improved#3]
Hi, 

I have a few questions about the code, I hope you don't mind.

- Why is the implementation of `match()` written the way it is?

```python
def match(text: str, regex: str) -> list:
    parsed = []
    parsed.append(re.findall(regex, text))
    parsed = sum(parsed, [])
    return parsed
```

Is there a benefit here over just doing `list(re.findall(regex, text))` ?

- How did you choose when to use `match()` vs `match_by_regex_search()`? 

- I notice that the benchmark folder only contains the results. Any chance you can also include the code that produced these results?

**Comment by brootware** [comment]
Hello @erezsh , Thank you for catching the implementation of `match()`. I missed out to change this back as I was testing out the regexes.

The choice between `match()` and `match_by_regex_search()` was mainly because of the accuracy in regex matching during the test. `match()` does a findall. It's great for finding in 1 text globs. But when there are `\n` new lines in the text I found `match_by_regex_search()` to be more accurate. Consider the code below, you can test it out too!

```python
import crim as cregex

data="""John, please get that article on www.linkedin.com to me by 5:00PM on Jan 9th 2012. 4:00 would be ideal, actually. If you have any questions, You can reach me at (519)-236-2723x341 or get in touch with my associate at brute@tech.gov.sg
this is my IP: 102.23.5.1
My router is : 10.10.10.1
71.159.188.33
81.141.167.45
165.65.59.139
64.248.67.225

https://tech.gov.sg
git@github.com:brootware/awesome-cyber-security-university.git

My email is harold@gmail.com

this is my IP: 102.23.5.1
My router is: 10.10.10.1
71.159.188.33
81.141.167.45
165.65.59.139
64.248.67.225

Base64 data
QVBJX1RPS0VO
UzNjcjN0UGFzc3dvcmQ=
U3VwM3JTM2NyZXRQQHNzd29yZA==

Card_Number,Card_Family,Credit_Limit,Cust_ID
8638-5407-3631-8196,Premium,530000,CC67088
7106-4239-7093-1515,Gold,18000,CC12076
6492-5655-8241-3530,Premium,596000,CC97173
2868-5606-5152-5706,Gold,27000,CC55858
1438-6906-2509-8219,Platinum,142000,CC90518
2764-7023-8396-5255,Gold,50000,CC49168
4864-7119-5608-7611,Premium,781000,CC66746
5160-8427-6529-3274,Premium,490000,CC28930
6691-5105-1556-4131,Premium,640000,CC76766
1481-2536-2178-7547,Premium,653000,CC18007
1355-1728-8274-9593,Premium,660000,CC232679621-6787-7890-7470,Platinum,53000,CC52613
6385-4594-8055-9081,Premium,737000,CC96267
2595-8621-2855-9119,Premium,564000,CC22050
7214-4915-6387-5429,Platinum,172000,CC72302
7908-3850-6633-2606,Gold,43000,CC71044
"""

one_line = "John, please get that article on www.linkedin.com to me by 5:00PM on Jan 9th 2012. 4:00 would be ideal, actually or 5:30 P.M. If you have any questions, You can reach me at (519)-236-2723x341 or get in touch with my associate at harold_smith@gmail.com. You can find my ip address at 127.0.0.1 or at 64.248.67.225. I also have a secret protected with md5 8a2292371ee60f8212096c06fe3335fd. The internal webpage to get the article from is https://internal.sharepoint.edu.au. My private ip address is 10.10.10.1"

url_test_match = cregex.match(one_line,cregex.regex_map["links"])
print(url_test_match)
# ['www.linkedin.com', 'gmail.com', 'https://internal.sharepoint.edu.au']

url_test_search = cregex.match_by_regex_search(one_line, cregex.regex_map["links"])
print(url_test_search)
# # ['www.linkedin.com', 'gmail.com', 'https://internal.sharepoint.edu.au']

url_test_match = cregex.match(data,cregex.regex_map["links"])
print(url_test_match)
# ['www.linkedin.com', 'tech.gov.sg', 'https://tech.gov.sg', 'github.com', 'awesome-cyber-security-university.gi', 'gmail.com']

url_test_search = cregex.match_by_regex_search(data, cregex.regex_map["links"])
print(url_test_search)
# ['www.linkedin.com', 'tech.gov.sg', 'https://tech.gov.sg', 'github.com', 'gmail.com']
```

I will be upload the benchmark codes in the folder with the next push!.

**Comment by erezsh** [comment]
Thanks! Another thing, if I may hijack this issue for it.

Some of the function names override the regex names. For example, `phones_with_exts`, `btc_address`, and more. That means the only way to access those regexes is through `regex_map`, which is a little awkward.

I personally have use for accessing them directly, thorugh `crim.email`, etc., and I think other might too!

**Comment by brootware** [comment]
Ah, yes you are right @erezsh .  They're being shadowed in a way. I'm thinking of appending `regex` to the regex variables as a fix. Please do let me know too if there are better alternatives to this.

**Comment by erezsh** [comment]
Sounds like a reasonable approach to me. Another possible prefix is `re_`.

**Comment by brootware** [comment]
I have incorporated your suggestion with the latest release at https://github.com/brootware/commonregex-improved/releases/tag/v1.0.2. I will be closing this issue for now. Please create a new one if you come across anything. Thank you so much for your suggestions and improvements!
